# Instructions how to build for netlify
[build]
  command = "npm install && npm run build"
  publish = "dist/"

#
# We use Vue router with history mode. Therefore redirect all requests to /index.html [1].
# Using [[redirects]] (as instructed in [2]) did not seem to work. However, placing a 
# `_redirects` file in the public directory did work, see [3]
#
# See
#  [1] https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations) 
#  [2] https://www.netlify.com/docs/netlify-toml-reference/#getting-started
#  [3] https://stackoverflow.com/questions/47729023/add-redirects-file-to-root-path-for-vue-spa-hosted-on-netlify
#
